######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 27 15:02:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += main.hh mtextedit.hh netsocket.hh peer.hh routingtable.hh point2pointview.hh MPMEdit.hh
SOURCES += main.cc mtextedit.cc netsocket.cc peer.cc routingtable.cc point2pointview.cc MPMEdit.cc
